version: "v2.0"
port: 8050
mode: "dev"
start_time: "2006-01-01"
machine_id: 1

mysql:
  host: "172.17.0.3"
  port: 3306
  dbname: "bluebell"
  user: "root"
  password: "123456"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "172.17.0.2"
  port: 6379
  dbname: 0
  password: ""
  pool_size: 100

log:
  level: "Debug"
  filename: "config.log"
  max_size: 10
  max_age: 30
  max_backups: 5
